# (1)Implement different population representations.

In [47]:
# population - Collection of encoded candidate solutions
import numpy as np

# Y = w1x1 + w2x2 + w3x3 + w4x4 + w5x5  inputs values are (x1,x2,x3,x4,x5)=(-2,7,5,11,1).
#We are looking to find the parameters (weights) that maximize such equation

sols_per_pop = 8
num_weights = 5

# Defining the population size.

pop_size = (sols_per_pop,num_weights) # The population will have sol_per_pop chromosome where each chromosome has num_weights genes.



In [48]:
#Creating the initial population.
#(A) Float representation for genes

new_population_F = np.random.uniform(low=-5.0, high=5.0, size=pop_size)
new_population_F

array([[-3.39992391, -3.14636609, -4.72979249,  2.59388946,  3.36780766],
       [-1.38262056,  2.9689701 ,  2.70835541, -0.9003608 , -3.6413824 ],
       [ 4.44362653, -2.46306061,  4.74797989,  0.54478542, -0.00728528],
       [ 0.88855435,  1.91677303, -3.24648593,  4.04921468,  1.35257144],
       [-4.84153821, -0.35820781,  2.22282956,  3.85835105,  1.46246956],
       [-1.22933113,  3.380188  , -2.14838188, -3.40353611, -0.78442844],
       [-4.80090399,  1.12637212,  1.94279272, -1.06708177, -4.88481766],
       [-2.41186863,  4.95405425, -2.53175941,  1.40547272,  1.52413005]])

In [49]:
new_population_F.shape

(8, 5)

In [50]:
#(B) Integer representation for genes
new_population_I = np.random.randint(low=-5, high=10, size=pop_size)

In [51]:
new_population_I

array([[-1,  5,  9,  8, -1],
       [ 4,  7,  6, -2,  1],
       [ 8, -1,  6,  8,  7],
       [ 6, -1,  9,  2,  2],
       [-1,  1, -3,  8, -3],
       [ 6,  3, -1,  3,  0],
       [-1,  3,  2,  7,  6],
       [ 2,  6, -1, -5,  1]])

In [52]:
new_population_I.shape

(8, 5)

In [53]:
#(C) Binary representation for genes

In [54]:

new_population_B = np.random.randint(low=0, high=2, size=pop_size)

In [55]:
new_population_B

array([[0, 0, 1, 0, 0],
       [1, 1, 0, 0, 0],
       [1, 1, 0, 0, 0],
       [0, 1, 1, 0, 0],
       [0, 1, 0, 1, 0],
       [0, 1, 1, 0, 1],
       [0, 1, 1, 1, 0],
       [1, 0, 1, 0, 1]])

# (2)Implement all mutation and crossover operators available for integer representation and floating point representation.

## Binary Representaiton
* Mutation: Bitwise
* Recombination: one point crossover, n-point crossover, uniform crossover 

### Integer Representation
* Mutation: Random resetting, Creep
* Recombination: one point, n-point, uniform

### Real valued or floting point Representation
* Mutation: Uniform, non-uniform, self adaptive, uncorrelated, correlated
* Recombination: Simple, single, whole, blend

### Tree Representation
* Mutation: Replacing subtree with random tree
* Recombination: subtree crossover

In [87]:
# Float representation
import random
import pandas as pd
def fitness_func(population):
    
    fitness=[]
    for pop_row in population:
        fit=0
        fit=pop_row[0]*1-pop_row[1]*2+pop_row[2]*3-pop_row[3]*4 + pop_row[4]*6 # 1x-2y+3z-4a+6c
        
        fitness.append(fit)
    fitness =  [abs(ele) for ele in fitness] 
    print('The best population',population[fitness.index(min(fitness))])
    print('Best fitness value',min(fitness))
    return fitness

    
def select_parents(population, fitness):
    
    parents = []
    parent_ids=[]
#     fitness=abs(fitness)
    
    min_fitness_idx = numpy.where(fitness == numpy.min(fitness))[0][0]
    population=pd.DataFrame(population)
    parent_ids.append(min_fitness_idx)
    parents.append(list(population.iloc[min_fitness_idx,:]))
    
    fitness[min_fitness_idx]=9999
    
    min_fitness_idx = numpy.where(fitness == numpy.min(fitness))[0][0]
    parents.append(list(population.iloc[min_fitness_idx,:]))
    parent_ids.append(min_fitness_idx)
    
    return parents,parent_ids


def crossover(parents):
    
    #1-point crossover
    size=len(parents[0])
    n=random.randint(1,size-1)
    parents=pd.DataFrame(parents)

    cut1=parents.iloc[0,n:].copy()
    cut2=parents.iloc[1,n:].copy()
    
    parents.iloc[0,n:]=cut2
    parents.iloc[1,n:]=cut1
    

    return parents.values

def n_crossover(parents,n):
    print(parents[0])
    print(parents[1])
        
    #n-point crossover
    size=len(parents[0])
    n_idx=(random.sample(range(size), n))
    n_idx.sort()
    parents=pd.DataFrame(parents)
    print("\n N-points")
    print(n_idx)
    i=0
    while i<n:
        start=n_idx[i]
        
        if(i+1<n):
            end=n_idx[i+1]
            
        else:
            end=size-1
            
        cut1=parents.iloc[0,start:end].copy()
        cut2=parents.iloc[1,start:end].copy()

        parents.iloc[0,start:end]=cut2
        parents.iloc[1,start:end]=cut1
        
        i=i+2
    
    print("\n New Parents")
    print(parents.values)
    
    return parents.values

def mutation(parents):
    new_parent=[]
    for parent_row in parents:
        idx1=random.randint(0,len(parents[0])-1)
        idx2=random.randint(0,len(parents[0])-1)
        parent_row[idx1]=random.uniform(0,30)
        parent_row[idx2]=random.uniform(0,30)
        new_parent.append(list(parent_row))
    
    return list(new_parent)

def uniform_mutation(p1,p2):
        bit = random.randint(0,1)
        if(bit):
            p1[bit] = np.min(np.array([p1,p1])) + random.random()*( np.max(np.array([p1,p1])) - np.min(np.array([p1,p1])) )
            p2[bit] = np.min(np.array([p1,p1])) + random.random()*( np.max(np.array([p1,p1])) - np.min(np.array([p1,p1])) )
        else:
            p1[bit] = np.min(np.array([p1,p1])) + random.random()*( np.max(np.array([p1,p1])) - np.min(np.array([p1,p1])) )
            p2[bit] = np.min(np.array([p1,p1])) + random.random()*( np.max(np.array([p1,p1])) - np.min(np.array([p1,p1])) )
        return p1,p2

In [84]:
new_parents=n_crossover(new_population_F,4)

[ 0.          3.         -4.72979249  7.         15.        ]
[-3.39992391  2.9689701   2.         -0.9003608  -3.6413824 ]

 N-points
[0, 1, 2, 3]

 New Parents
[[-3.39992391e+00  3.00000000e+00  2.00000000e+00  7.00000000e+00
   1.50000000e+01]
 [ 0.00000000e+00  2.96897010e+00 -4.72979249e+00 -9.00360797e-01
  -3.64138240e+00]
 [ 4.44362653e+00 -2.46306061e+00  4.74797989e+00  5.44785419e-01
  -7.28528238e-03]
 [ 8.88554347e-01  1.91677303e+00 -3.24648593e+00  4.04921468e+00
   1.35257144e+00]
 [-4.84153821e+00 -3.58207814e-01  1.00000000e+00  2.00000000e+01
   2.30000000e+01]
 [ 2.72582624e+01  1.37700923e+01  7.91188673e+00  8.08378800e+00
   1.46246956e+00]
 [-1.00000000e+00  1.00000000e+00  9.00000000e+00  1.10000000e+01
   1.90000000e+01]
 [ 3.11132991e+00  9.42647860e+00  7.91188673e+00  3.85835105e+00
   1.46246956e+00]]


In [85]:
import numpy
print("fitness : ",fitness_func(new_population_F))
print("\n\n")
num_generations = 50
for generation in range(num_generations):
    print("Generation : ", generation)
    
    fitness=fitness_func(new_population_F)
    
    
    parents,parent_ids=select_parents(new_population_F,fitness)

    
    cross_parents=crossover(parents)

    
    new_parents=mutation(cross_parents)

   
    fitness_parents=fitness_func(parents)
    fitness_new_parents=fitness_func(new_parents)
    new_population=new_population_F
    
    for i,idx in enumerate(parent_ids):
        if(fitness_new_parents[i]<fitness_parents[i]):
            
            print("From: ")
            print(new_population[idx])
            print("To:")
            print(new_parents[i])
            new_population[idx]=new_parents[i]
        
    print(new_population)
    population=new_population

The best population [27.25826237 13.77009233  7.91188673  8.083788    1.46246956]
Best fitness value 0.10659675834808091
fitness :  [58.60007609464681, 38.37416890400641, 21.39083403826428, 20.765879631964594, 56.87487741977175, 0.10659675834808091, 94.0, 1.3354460632169953]



Generation :  0
The best population [27.25826237 13.77009233  7.91188673  8.083788    1.46246956]
Best fitness value 0.10659675834808091
The best population [27.25826237335241, 13.770092330876867, 7.911886728535899, 8.08378800237183, 1.4624695589888104]
Best fitness value 0.10659675834808091
The best population [3.1113299085560175, 28.525936122753073, 7.911886728535899, 1.2810283469625394, 1.4624695589888104]
Best fitness value 26.55417818525973
[[-3.39992391e+00  3.00000000e+00  2.00000000e+00  7.00000000e+00
   1.50000000e+01]
 [ 0.00000000e+00  2.96897010e+00 -4.72979249e+00 -9.00360797e-01
  -3.64138240e+00]
 [ 4.44362653e+00 -2.46306061e+00  4.74797989e+00  5.44785419e-01
  -7.28528238e-03]
 [ 8.88554347e-0

Best fitness value 0.10659675834808091
The best population [1.6360470647077607, 20.387063172388817, 7.911886728535899, 3.8583510454495755, 1.4624695589888104]
Best fitness value 22.061005922327617
[[-3.39992391e+00  3.00000000e+00  2.00000000e+00  7.00000000e+00
   1.50000000e+01]
 [ 0.00000000e+00  2.96897010e+00 -4.72979249e+00 -9.00360797e-01
  -3.64138240e+00]
 [ 4.44362653e+00 -2.46306061e+00  4.74797989e+00  5.44785419e-01
  -7.28528238e-03]
 [ 8.88554347e-01  1.91677303e+00 -3.24648593e+00  4.04921468e+00
   1.35257144e+00]
 [-4.84153821e+00 -3.58207814e-01  1.00000000e+00  2.00000000e+01
   2.30000000e+01]
 [ 2.72582624e+01  1.37700923e+01  7.91188673e+00  8.08378800e+00
   1.46246956e+00]
 [-1.00000000e+00  1.00000000e+00  9.00000000e+00  1.10000000e+01
   1.90000000e+01]
 [ 3.11132991e+00  9.42647860e+00  7.91188673e+00  3.85835105e+00
   1.46246956e+00]]
Generation :  32
The best population [27.25826237 13.77009233  7.91188673  8.083788    1.46246956]
Best fitness value 0.10

In [86]:
fitness_func(new_population)

The best population [27.25826237 13.77009233  7.91188673  8.083788    1.46246956]
Best fitness value 0.10659675834808091


[58.60007609464681,
 38.37416890400641,
 21.39083403826428,
 20.765879631964594,
 56.87487741977175,
 0.10659675834808091,
 94.0,
 1.3354460632169953]